### PR TITLE
Fix Humble App login

### PR DESCRIPTION
**Pull request by Zoullx**
It only took like three days, a ton of Googling and frustration, but I finally figured it out. I still want to refactor the urls and paths for the downloads of the extra files, but here's the implementation to fix the Humble App login issues.

### CODE REVIEW

**Comment by moraroy** [comment]
@Zoullx dang good job bro..im going to add this in thank you for fixing this! rest up brother!!!

**Comment by frodonl** [comment]
Not sure what's causing this, but when I try to use Humble after installing it this way - and trying to log on while in desktop mode, it gives me the standard pop up, with two options, of which I choose "Sign in to your Humble account". 

That opens Firefox, where I am indeed logged on. 

When then clicking "Allow access", I am given the option to choose an application to open 'x-scheme-handler/humble'.

I there choose "Humble Games Collection (Login)". And come back to the same pop-up from before.

**Comment by Zoullx** [comment]
Could you take some screenshots/pictures to show me the process and what you're seeing?

**Comment by frodonl** [comment]
I tried the xdg-mime command, as suggested, but it does not seem to do anything. These are screenshots - the fourth looks like the first, but is actually the only thing I see (still).
Screenshot_20230621_192112
Screenshot_20230621_192131
Screenshot_20230621_192210
Screenshot_20230621_192214

**Comment by Zoullx** [comment]
Ahh, I see now what's going on. So, it kind of is what I thought, but there seems to be an extra piece here. Have you ever installed the Humble App with Lutris? So, the name of the application to handle the `x-scheme-handler/humble` is actually `Humble App (Login)` and not `Humble Games Collection (Login)`. `Humble App (Login)` is specific to ours and points to our specific handler, whereas `Humble Games Collection (Login)` is specific to the Lutris installation of the Humble App and points to their specific handler and these handlers do different things so you have to make sure that you're pointing to the specific handler for the specific installation.

**Comment by frodonl** [comment]
Okay, that makes sense. Weirdly I do not see the other one. I will see if I can clean up the one from Lutris.

**Comment by Zoullx** [comment]
Ok, that would actually make sense because they do actually share the same name. So, you would actually only be able to have one or the other. Which means that our installation left the other one because it saw that you already "had" that file. I guess I should probably think about changing the names in case someone is coming from a Lutris installation. If you delete this file: `$HOME/.local/share/applications/Humble-scheme-handler.desktop` and try the installation again, it should fix the issue by installing our version of that application.

**Comment by frodonl** [comment]
Yeah, I just found the file and was doing that. And yes, that did indeed to the trick.

Thanks for the quick reactions!

**Comment by Zoullx** [comment]
No problem. And thanks for letting me know. Definitely something to think about for people that have previously installed the Humble App through Lutris.

**Comment by moraroy** [comment]
@Zoullx hey brother good job on the humble fix

**Comment by brianx87** [comment]
Starting having this issue, I can't login, the humble login opens firefox and allows me to grant access but it doesn't complete the process. I haven't installed using Lutris.

**Comment by moraroy** [comment]
@brianx87 you installed it with lutris?

**Comment by brianx87** [comment]
> I haven't installed using Lutris.

> @brianx87 you installed it with lutris?

No

**Pull request merged**
