### PR TITLE
add installation to vk play launcher

### PR DESCRIPTION
**Pull request by mertsalovda**
Hello! Prepared a pull request with the addition of VK Play.

### CODE REVIEW

**Comment by moraroy** [comment]
Hey good work! Unfortunately for the time being I won't be able to add any new launchers just yet until the Plug-in for deck loader is passed through its currently in testing. Once that is released then I could concentrate on adding new launchers.

**Comment by moraroy** [comment]
@mertsalovda also dont forget to add the App id in the list of appids....its new code in the "Start Fresh" section in order to delete the Shader Cache associated with the launcher. You can find the appid for the launcher in the log when you install it.

**Comment by mertsalovda** [comment]
@moraroy 
Added app id.
Took the value from the log file
```app_id_to_name: {3494943831: 'VK Play'}```
This is right?

**Comment by moraroy** [comment]
@mertsalovda yes that's correct! It's just for the shader cache, also... not sure if you're aware I looked up the steamgrid cover art and steamgrid has the game called like this.... https://www.steamgriddb.com/game/5418177p usually I would match the Steam Shortcut name with the steamGriddb so that way it's easier for people who have the plug in to add the cover art. So you may want to change that in the python code to match the Steam Shortcut so its named correctly if that makes sense.

**Comment by mertsalovda** [comment]
I plan to add images to SteamGriddb myself, which I will take from the VK Play design system.

**Comment by moraroy** [comment]
@mertsalovda gotcha OK no worries!

**Pull request merged**
