### PR TITLE
Add .desktop file to always download and use the latest version of your script

### PR DESCRIPTION
**Pull request by cchrkk**
and no need to set the .sh file executable.

### CODE REVIEW

**Comment by cchrkk** [comment]
You just move the .desktop file to desktop, double click it and you're good.

**Comment by moraroy** [comment]
i like this idea lets do it! @cchrkk  just so i understand though, so when people download the zip this other file will be with it? and you throw it on the desktop and then that updates the file with every new release?

**Comment by moraroy** [comment]
idk how github works but im going to add it we will see how it goes, ill release it with 2.4

**Comment by cchrkk** [comment]
> idk how github works but im going to add it we will see how it goes, ill release it with 2.4

Hey 😉 yes it's easy as downloading the desktop file, moving It to the desktop and double clicking it. It fetches the .sh file from main branch on your GitHub and runs it

**Pull request merged**
