### PR TITLE
Add tooling

### PR DESCRIPTION
**Pull request by pythoninthegrass**
Thus far, no changes have been made to the main program logic in `NonSteamLaunchers.sh`. Just adding scaffolding around the repo for contributors.

Of note is the [devcontainer](https://code.visualstudio.com/docs/devcontainers/containers) with [shellcheck](https://www.shellcheck.net/wiki/Home), [bash ide](https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode), and [editorconfig](https://editorconfig.org/) plugins installed. Mimics local dev environment.

What's been added:
- vscode (devcontainer w/default extensions)
- github (dependabot if any non-stdlib modules get installed)
- gitignore (generated comprehensive python exclusions)
- editorconfig (auto formatting locally)
- shellcheckrc (lint shell scripts w/exclusions)
- tool-versions (asdf)

Plan to streamline `NonSteamLaunchers.sh` with case statements, functions, and general formatting (hence shellcheck + bash ide).

### CODE REVIEW

**Comment by moraroy** [comment]
@pythoninthegrass gosh this is alot. Im not sure what some of these do exactly haha this would help contributors in a big way here on github or when other users fork?

**Comment by pythoninthegrass** [comment]
No worries, Roy!

Yep! DevContainers use Docker to recreate a single environment where each contributor can have the same tooling regardless of their host machine.

EditorConfig takes care of formatting markdown, python, and shell scripts as long as you have the file in the top-level directory of the repo.

Bash IDE uses shellcheck to act as a language server for shell scripts. It has useful features like giving descriptions of functions based on comments, tracking where variable were declared, and refactoring function and variable names among others.

asdf is a wrapper for various runtime plugin but for our purposes, it handles python and poetry ; the latter takes care of python dependencies (a la pip), virtual environments (venv/virtualenv), and packaging.

I can add documentation later today if you'd like?
________________________________

**Comment by pythoninthegrass** [comment]
> I can add documentation later today if you'd like?
Done!

Also, might be worth refactoring the `README.md` to use standard markdown headings (e.g., `#`) vs. HTML formatting (`<h1 align="center">`), unless you have a strong preference for centered text.

**Comment by moraroy** [comment]
@pythoninthegrass interesting ok... sounds good. I do like the centered text! But I'm open to new possibilites!

**Comment by moraroy** [comment]
@pythoninthegrass also, I haven't optimized the bash code yet. I still have to do that. But I'll ad in your pull!

**Comment by pythoninthegrass** [comment]
Glad you merged the PR @moraroy! Look forward to helping out the project 🚀

**Pull request merged**
