### PR TITLE
Add Glyph Launcher

### PR DESCRIPTION
**Pull request by Zoullx**

### CODE REVIEW

**Comment by moraroy** [comment]
@Zoullx I'm really hesitant to add another launcher right now to be honest. I wanted to get all the bugs from the other parts of the code first... but if you can assure this works and not only that.. have you checked to see if you can run this in quiet mode or passive? I use a long command during the runtime to check this first. For example. Run glyph.exe  /q  or if it's an msi file then it's whole different structure you have to check for.

**Comment by Zoullx** [comment]
I've created chocolatey packages for all of these launchers and, unfortunately, there's no easy passive flag that can be passed to the launcher. However, I have checked to see if the install works on my own Steam Deck before creating the PR, but again, you have to progress through the installer manually. I am currently working on figuring out if there's some extra effort that can be put in to silently install the Glyph Launcher with the chocolatey package, but so far, I've only figured out how to uninstall silently. In terms of other issues with the script, I have fixes for an issue with not being able to move Rockstar to the SD card and I'm currently looking into how to fix the Humble Bundle login issue by looking at how it's done with Lutris and I just pushed a fix for the recreation of shortcuts in Steam.

**Comment by moraroy** [comment]
@Zoullx wow you're amazing bro.. seriously these are all fixes that I've been thinking about but didn't know how to tackle yet, you're a blessing. Thank you. Yeah I merged your commit for the SD card, I couldn't believe I forgot to add that check haha and thank you for this shortcut fix as well. I didn't know capitalizing that was important for duplicates.

**Comment by Zoullx** [comment]
Hey, I installed all of these launchers manually on my Steam Deck originally, so it's really nice to have a script that does it all automatically, so thank you for making the script in the first place. As for the shortcuts, if Steam saves the shortcuts, it makes the appname and exe properties lowercase. Then when the script would try and check the AppName and Exe properties they would be blank because casing for stuff like that is important in Python. As for the Humble login issue, I'm close, I'm only missing the url being passed to the script, so then it doesn't get sent to the exe, but as soon as I figure that out I should have the PR good to go for that.

**Comment by moraroy** [comment]
@Zoullx today I learned! Haha heck yeah as soon you got it let me know and I add it in! Honestly python is kind of annoying but I'm getting used to it. This is going to sound bad but forgive my spaghetti code I know it's a mess. Once things are stable I'll work on optimizing, going from bash and mixing in python is kind of hard but I'm getting used to it LOL

**Comment by Zoullx** [comment]
One of the next PRs that I'd like to put together is refactoring out a lot of the duplicated code into generic functions and then just call them passing in the relevant parameters.

**Comment by moraroy** [comment]
@Zoullx looking forward to it brother! That would be tight! It would definitely help get rid of redundancies for sure. I'm going to go ahead and push this to main! Thank you again. 😊

**Comment by moraroy** [comment]
@Zoullx I know this pull request was closed but bro! I hope you have been well! I just stumbled upon your chocolatey for Rockstar Games Launcher haha was wondering what were your thoughts in installing that silently? I also just realized you have other silent launchers as well and I wanted to pick your brain on silently installing things. If you have a discord, hit me up it's @moraroy

**Pull request merged**
